// <auto-generated />
namespace WebSaleCable.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatetable10072304 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetable10072304));
        
        string IMigrationMetadata.Id
        {
            get { return "201804231507437_updatetable10072304"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
