// <auto-generated />
namespace WebSaleCable.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatecolum200324042018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecolum200324042018));
        
        string IMigrationMetadata.Id
        {
            get { return "201804240820433_updatecolum200324042018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
